# Python Django with uv package manager
# Test a Django project on multiple versions of Python using uv.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: 'Self Hosted Rehaan'

strategy:
  matrix:
    Python313:
      PYTHON_VERSION: '3.13'
  maxParallel: 1

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- script: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
    echo "##vso[task.prependpath]$HOME/.cargo/bin"
  displayName: 'Install uv'

- script: |
    uv sync --frozen
  displayName: 'Install dependencies with uv'

- script: |
    uv run python manage.py test
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Python $(PYTHON_VERSION)'
  condition: succeededOrFailed()