# azure-pipelines.yml
trigger: none
pr: none

# Agentless
pool: server

stages:
- stage: Connected
  displayName: "Connection established"
  jobs:
  - job: AgentlessNoOp
    displayName: "No-op server job"
    steps:
    # Agentless built-in task – does nothing, completes immediately
    - task: Delay@1
      inputs:
        delayForMinutes: '0'
      displayName: "No-op (agentless)"
